### ISSUE TITLE
more than single added node crashes

### ISSUE THREAD

**Issue by RoyiRa** [allenai/pybart#33]
Hi,

Some sentences seem to crash PyBart when config={'enhanced_extra':True', 'enhanced_plus_plus':True}. 

For instance, running:

 "London is home to many museums, galleries, and other institutions, many of which are free of admission charges and are major tourist attractions as well as playing a research role".

Will result in the error:

London is home to many museums, galleries, and other institutions, many of which are free of admission charges and are major tourist attractions as well as playing a research role
Traceback (most recent call last):
  File "/Users/royi/missing_elements_exploration/process_data.py", line 198, in <module>
    squad()
  File "/Users/royi/missing_elements_exploration/process_data.py", line 105, in squad
    doc = pybart(sent_)
  File "/Users/royi/RLProjcOURSE/venv/lib/python3.8/site-packages/spacy/language.py", line 995, in __call__
    error_handler(name, proc, [doc], e)
  File "/Users/royi/RLProjcOURSE/venv/lib/python3.8/site-packages/spacy/util.py", line 1498, in raise_error
    raise e
  File "/Users/royi/RLProjcOURSE/venv/lib/python3.8/site-packages/spacy/language.py", line 990, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/Users/royi/RLProjcOURSE/venv/lib/python3.8/site-packages/pybart/api.py", line 52, in __call__
    converted_sents, convs_done = convert_spacy_doc(doc, *self.config, self.conversions)
  File "/Users/royi/RLProjcOURSE/venv/lib/python3.8/site-packages/pybart/api.py", line 41, in convert_spacy_doc
    enhance_to_spacy_doc(doc, converted)
  File "/Users/royi/RLProjcOURSE/venv/lib/python3.8/site-packages/pybart/spacy_wrapper.py", line 94, in enhance_to_spacy_doc
    orig_doc._.parent_graphs_per_sent.append(Graph(orig_doc, name="pybart", nodes=nodes, edges=edges, labels=labels))
  File "spacy/tokens/graph.pyx", line 402, in spacy.tokens.graph.Graph.__init__
  File "spacy/tokens/graph.pyx", line 71, in spacy.tokens.graph.Node.__init__
IndexError: Node index 34 out of bounds (34)

I am using the Spacy pipeline and "en_model_trf". If you try different models, different sentences will crash PyBart.

Also, for some sentences, I get different dependency graphs in the demo and my system. Is it possible to provide the configuration and model you use for the demo version? 

Thanks

**Comment by aryehgigi** [comment]
Hi @RoyiRa first of all thanks for your interest and collaboration!

regarding the sentence you found that cause a crash: i was able to reproduce it with even a simpler sentence:
`London is home to many museums other institutions`.
I will check it out. Thanks a lot

regarding other sentences that crashes other models - please let me know by opening new issues with the specific cases just like you did here - so i can reproduce and fix.

regarding different graphs for same model on different thats weird. please try to reproduce and send a snapshot of the demo page and on your local machine in a new issue. 
The demo runs the trf model + pybart version 3.2.1 (to this date). maybe the difference is in the tokenization - IIRC the tokenization in the demo is a simple - `text.split(" ")`.

pybart has been massively upgraded with many new features and fixes - but obviously **_no good code goes unbugedness_** :)
